//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VulturDeliverys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conexion
    {
        public int ConexionID { get; set; }
        public Nullable<int> EnvioID { get; set; }
        public Nullable<int> CiudadOrigenID { get; set; }
        public Nullable<int> CiudadDestinoID { get; set; }
        public Nullable<System.DateTime> FechaHoraSalida { get; set; }
        public Nullable<System.DateTime> FechaHoraLlegada { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Ciudad Ciudad1 { get; set; }
        public virtual Envio Envio { get; set; }
    }
}
