//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VulturDeliverys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Envio()
        {
            this.Conexion = new HashSet<Conexion>();
            this.Trazabilidad = new HashSet<Trazabilidad>();
        }
    
        public int EnvioID { get; set; }
        public Nullable<int> EmisorID { get; set; }
        public Nullable<int> ReceptorID { get; set; }
        public string DireccionOrigen { get; set; }
        public string DireccionDestino { get; set; }
        public string TelefonoContacto { get; set; }
        public string DescripcionPaquete { get; set; }
        public Nullable<decimal> PesoPaquete { get; set; }
        public Nullable<decimal> ValorEnvio { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conexion> Conexion { get; set; }
        public virtual Emisor Emisor { get; set; }
        public virtual Receptor Receptor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trazabilidad> Trazabilidad { get; set; }
    }
}
